export const NITRO_DURATION_BADGES = [
    'NitroBronze',
    'NitroSilver',
    'NitroGold',
    'NitroPlatinum',
    'NitroDiamond',
    'NitroEmerald',
    'NitroRuby',
    'NitroOpal'
];

export const HQ_BADGES = [
    'NitroDiamond',
    'NitroEmerald',
    'NitroRuby',
    'NitroOpal',
    'PremiumEarlySupporter',
    'VerifiedDeveloper',
    'BoostLevel8',
    'BoostLevel9',
    'Staff',
    'Partner',
    'Oldstaff',
    'Alumni',
    'CertifiedModerator',
    'BugHunterLevel1',
    'BugHunterLevel2'
];

export const BADGE_EMOJI_NAMES = {
    Staff: 'staff',
    Partner: 'partner',
    Oldstaff: 'oldstaff',
    Alumni: 'alumni',
    Hypesquad: 'events',
    HypeSquadOnlineHouse1: 'HypeSquadOnlineHouse1',
    HypeSquadOnlineHouse2: 'HypeSquadOnlineHouse2',
    HypeSquadOnlineHouse3: 'HypeSquadOnlineHouse3',
    BugHunterLevel1: 'bughunter1',
    BugHunterLevel2: 'bughunter2',
    VerifiedDeveloper: 'earlydev',
    Nitro: 'nitro_basic',
    NitroBasic: 'nitro_basic',
    NitroClassic: 'nitro_basic',
    PremiumEarlySupporter: 'early',
    Quest: 'Quest',
    NitroBronze: 'nitro_bronze',
    NitroSilver: 'nitro_silver',
    NitroGold: 'nitro_gold',
    NitroPlatinum: 'nitro_platinum',
    NitroDiamond: 'nitro_diamond',
    NitroEmerald: 'nitro_emerald',
    NitroRuby: 'nitro_ruby',
    NitroOpal: 'nitro_opal',
    BoostLevel1: 'BoostLevel1',
    BoostLevel2: 'BoostLevel2',
    BoostLevel3: 'BoostLevel3',
    BoostLevel4: 'BoostLevel4',
    BoostLevel5: 'BoostLevel5',
    BoostLevel6: 'BoostLevel6',
    BoostLevel7: 'BoostLevel7',
    BoostLevel8: 'BoostLevel8',
    BoostLevel9: 'BoostLevel9'
};

export const SCRAP_BADGE_KEYS = [
    'NitroBronze',
    'NitroSilver',
    'NitroGold',
    'NitroPlatinum',
    'NitroDiamond',
    'NitroEmerald',
    'NitroRuby',
    'NitroOpal',
    'PremiumEarlySupporter',
    'VerifiedDeveloper',
    'Quest',
    'BoostLevel3',
    'BoostLevel4',
    'BoostLevel5',
    'BoostLevel6',
    'BoostLevel7',
    'BoostLevel8',
    'BoostLevel9',
    'BugHunterLevel1',
    'BugHunterLevel2',
    'Hypesquad',
    'HypeSquadOnlineHouse1',
    'HypeSquadOnlineHouse2',
    'HypeSquadOnlineHouse3',
    'Partner',
    'Staff',
    'Oldstaff',
    'Alumni'
];
